name: smoke test
description: smoke test the devcontainers
inputs:
  template:
    description: Template to test
    required: true

runs:
  using: composite
  steps:
    - name: Build template
      id: build_template
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.template }}
